# Generated by Django 5.1.6 on 2025-02-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='view_count',
            field=models.IntegerField(default=1),
        ),
    ]
